name: Compile Synapse Link API

on:
  push:
    branches: ["main"]

env:
  APP_PACKAGE_PATH: 'SynapseLinkAutomations.Api\SynapseLinkAutomations.Api.csproj'       
jobs:
  build-and-deploy:
    runs-on: windows-latest 
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh 
      run: |
        pushd '${{ env.APP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

