name: Compile Synapse Link API

on:
  push:
    branches: ["main"]

env:
  DOTNET_VERSION: '8.0.x'  # Specify the .NET version
  APP_PACKAGE_PATH: 'SynapseLinkAutomations.Api\SynapseLinkAutomations.Api.csproj'

jobs:
  build-and-deploy:
    runs-on: windows-latest 
    environment: dev
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Resolve Project Dependencies Using Dotnet
      shell: pwsh
      run: |
        dotnet build $env:APP_PACKAGE_PATH --configuration Release --output ./output

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: SynapseLinkCompiledOutput
        path: ./output/**
        if-no-files-found: error
